import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Topbar from "./components/Topbar";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Buy Facebook Followers | Buy Real FB Profile Followers & Likes | Socialize Club",
  description: "Generated by create next app",
  alternates: {
    canonical: 'https://www.socializeclub.com/',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
        <Topbar/>
        <Navbar/>
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
